### ISSUE TITLE
Issue with Node version 10.x

### ISSUE THREAD

**Issue by Codezhak** [uatisdeproblem/aws-wkhtmltopdf#1]
Thanks for this awesome package.But we faced an issue recently with this package that AWS limited the support for Node js 8.10 in lambda and we are forced to upgrade lambda to version 10.x.The binary for wkhtmltopdf added with this package is not working.It is showing Error code 127.

**Comment by uatisdeproblem** [comment]
Hey buddy! Unfortunately, we didn't find a way to include [the missing libraries](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4523) to make wkhtmltopdf work in Node 10.x.

Therefore, we completely changed approach and we moved towards this solution, that works quite well for us :) 

https://medium.com/@jlaitio/generating-pdfs-with-aws-lambda-nodejs-10-runtimes-the-hard-and-easy-way-5316062dd253 

We will archive this repo since it's kind of useless for anyone upgrading from Node 8.
